# Generated by Django 3.2.5 on 2021-07-21 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=500, verbose_name='Issue Number')),
                ('issue_title', models.CharField(max_length=1000, verbose_name='Issue Title')),
                ('issue_cover', models.ImageField(upload_to='comic_issues', verbose_name='Issue cover')),
                ('issue_description', models.TextField(verbose_name='Description')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'dislike')], max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_slug', models.SlugField(default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by: ')),
            ],
            options={
                'verbose_name': 'Comic Issue',
                'verbose_name_plural': 'Comic Issues',
            },
        ),
        migrations.CreateModel(
            name='IssuePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.FileField(upload_to='comic_issues_files/panels/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by: ')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comicissue')),
            ],
            options={
                'verbose_name': 'IssuePanel',
                'verbose_name_plural': 'IssuePanels',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comicissue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ComicSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Series Title')),
                ('cover', models.ImageField(upload_to='comic_series', verbose_name='Series cover')),
                ('description', models.TextField(verbose_name='Description')),
                ('other_artists', models.CharField(max_length=250, verbose_name='Associated artists')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by: ')),
            ],
            options={
                'verbose_name': 'Comic Series',
                'verbose_name_plural': 'Comic Series',
            },
        ),
        migrations.AddField(
            model_name='comicissue',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comicseries', verbose_name='Series Title'),
        ),
    ]
