# Generated by Django 3.2.5 on 2021-07-30 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ComicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=250, verbose_name='Type')),
            ],
        ),
        migrations.RenameField(
            model_name='comicissue',
            old_name='title',
            new_name='series',
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='issue_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='comicissue',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'dislike')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='comicseries',
            name='com_category',
            field=models.ManyToManyField(blank=True, to='comics.ComicCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='comicseries',
            name='com_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comics.comictype', verbose_name='Type'),
        ),
    ]
