# Generated by Django 3.2.5 on 2021-08-03 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20210730_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicseries',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 12, 8, 13, 810431, tzinfo=utc)),
        ),
    ]
