# Generated by Django 3.2.5 on 2021-08-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comicseries_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicseries',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
