# Generated by Django 3.2.5 on 2021-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'staff'), ('verified', 'verified'), ('reader', 'reader')], max_length=250, null=True),
        ),
    ]
